import random

from selenium.webdriver.common.by import By


class MainPageLocators:
    INPUT_EMAIL = (By.XPATH, "//input[@id='email']")
    INPUT_PASSWORD = (By.XPATH, "//input[@id='password']")
    LOG_IN_BUTTON = (By.XPATH, "//button[@class='button button-big button-blue']")
    GOOD_EVENING_TEXT = (By.XPATH, "//div[@class='title'][contains(.,'Good')]")
    SMS_BUTTON = (By.XPATH, '//explorer-menu-item[@data-cy="sms-button"]')
    CREATE_CAMPANING_BUTTON = (By.XPATH, '//button[@class="button"]')
    MESSAGING_BUTTON = (By.XPATH, "//div[text()='Messaging']")
    INPUT_CAMPANING_NAME = (By.XPATH, '//input[@placeholder="Campaign name"]')
    CHOSSE_PROJECT = (By.XPATH, "//span[text()='Choose project']")
    CREATE_NEW_PROJECT_BUTTON = (By.XPATH, "//button[text()='CREATE NEW PROJECT']")
    INPUT_PROJECT_NAME = (By.XPATH, '//input[@placeholder="Project name"]')
    NEXT_BUTTON = (By.XPATH, '//button[text()=" NEXT "]')
    SELECT_WANT_USE_SMS = (By.XPATH, '//label[@for="sms"]')
    BUTTON_DONE = (By.XPATH, '//button[text()=" DONE "]')
    MARKETING = (By.XPATH, '//label[@for="marketing"]')
    SMS_TEMPLATE_DIV = (By.XPATH, "//div[@class='image-block']")
    BUTTON_DESIGN = (By.XPATH, '//button[text()=" DESIGN "]')
    SELECT_PROFILE = (By.XPATH, '//div[@class="search-container"]')
    PROFILE = (By.XPATH, '//div[@class="profile"]')
    ADD_LIST_BUTTON = (By.XPATH, '//div[@class="launch-settings-list"]')
    MY_BOARD_CHECKBOX = (By.XPATH, "//tr[2]/td[1]/megadash-checkbox/div/label[1]")
    ADD_RECIPIENCT_DONE_BUTTON = (By.XPATH, '//div[text()=" DONE "]')
    MESSAGE_EDITOR = (By.XPATH, '//div[@class="editor"]')
    EMOJY_BUTTON = (By.XPATH, '//button[@class="messaging-editor-action emoji-action"]')
    EMOJY_LIST = (By.XPATH, f'//div[@class="emoji-item ng-star-inserted"]')
    PERSONALIZD_BUTTON = (By.XPATH, '//button[@class="messaging-editor-action dynamic-action"]')
    DROP_DOWN_PERSONALIZD = (By.XPATH, '//p-dropdown[@id="editor-dynamic-field"]')
    LIST_PERSONALIZD = (By.XPATH, f'//ul[@role="listbox"]/p-dropdownitem{[random.randint(1, 4)]}')
    INPUT_VALUE = (By.XPATH, '//input[@id="editor-dynamic"]')
    INSERT_BUTTON = (By.XPATH, '//button[text()=" Insert "]')
    INSERT_LINK_BUTTON = (By.XPATH, '//button[@class="messaging-editor-action link-action"]')
    INPUT_URL = (By.XPATH, '//input[@id="editor-link"]')
    SEND_SMS_BUTTON = (By.XPATH, '//button[text()=" SEND SMS "]')
    BUTTON_SENT = (By.XPATH, '//button[text()=" SENT "]')
    BUTTON_PUBLISH = (By.XPATH, '//button[@class="button button-big button-blue"]')
    SUCCESS_MESSAGE = (By.XPATH, '//div[text()="Success"]')
    FINISH_DONE = (By.XPATH, '//div[@class="button button-big button-blue"]')
